#!/bin/bash
found_rom_path=""
rom_hash=""
rom_filename_pattern=""
rom_base_path="/tmp"
locate_rom(){
        readarray -t FIND_OUTPUT < <(find "$rom_base_path" -name "$rom_filename_pattern" -exec cksum {} \;)
        for line in "${FIND_OUTPUT[@]}"
        do
                echo "$line" | awk '{print $1'}
                if [ $(echo "$line" | awk '{print $1}') == $rom_hash ]; then
                        found_rom_path=$(echo "$line" | awk '{$1=$2=""; print $0}')
                        echo "found $line"
                        break;
                fi
        done
}
mv randomizerlauncher.ini randomizerlauncher.ini.prev
echo "#Base DIRs and base setup\n\n" > randomizerlauncher.ini
BaseGameDir=$(randomizers/mbc list_rom_for NES | awk -F ' ' '{print $2}' | awk -F '/' 'sub(FS $NF,x)' | awk -F '/' 'sub(FS $NF,x)' | tail -1)
echo "BaseGameDir=$BaseGameDir\n" >> randomizerlauncher.ini
BaseNesDir=$(randomizers/mbc list_rom_for NES | awk -F ' ' '{print $2}' | awk -F '/' '{print $(NF-1)}'| tail -1)
echo "BaseNesDir=$BaseNesDir\n" >> randomizerlauncher.ini
BaseSnesDir=$(randomizers/mbc list_rom_for SNES | awk -F ' ' '{print $2}' | awk -F '/' '{print $(NF-1)}')
echo "BaseSnesDir=$BaseSnesDir\n" >> randomizerlauncher.ini
BaseGameboyDir=$(randomizers/mbc list_rom_for GAMEBOY | awk -F ' ' '{print $2}' | awk -F '/' '{print $(NF-1)}'| tail -1)
echo "BaseGameboyDir=$BaseGameboyDir\n" >> randomizerlauncher.ini
BaseGBADir=$(randomizers/mbc list_rom_for GBA | awk -F ' ' '{print $2}' | awk -F '/' '{print $(NF-1)}'| tail -1)
echo "BaseGBADir=$BaseGBADir\n" >> randomizerlauncher.ini
BaseN64Dir=$(randomizers/mbc list_rom_for N64 | awk -F ' ' '{print $2}' | awk -F '/' '{print $(NF-1)}'| tail -1)
echo "BaseN64Dir=$BaseN64Dir\n" >> randomizerlauncher.ini
BaseGenesisDir=$(randomizers/mbc list_rom_for MEGADRIVE | awk -F ' ' '{print $2}' | awk -F '/' '{print $(NF-1)}'| tail -1)
if [ "$BaseGenesisDir" == "" ]; then
		BaseGenesisDir=$(randomizers/mbc list_rom_for GENESIS | awk -F ' ' '{print $2}' | awk -F '/' '{print $(NF-1)}'| tail -1)
fi
if [ "$BaseGenesisDir" == "" ]; then
		BaseGenesisDir=$(randomizers/mbc list_rom_for GENESIS.BIN | awk -F ' ' '{print $2}' | awk -F '/' '{print $(NF-1)}'| tail -1)
fi
echo "BaseGenesisDir=$BaseGenesisDir\n" >> randomizerlauncher.ini
BaseSMSDir=$(randomizers/mbc list_rom_for SMS | awk -F ' ' '{print $2}' | awk -F '/' '{print $(NF-1)}'| tail -1)
echo "BaseSMSDir=$BaseSMSDir\n" >> randomizerlauncher.ini
BasePSXDir=$(randomizers/mbc list_rom_for PSX | awk -F ' ' '{print $2}' | awk -F '/' '{print $(NF-1)}'| tail -1)
echo "BasePSXDir=$BasePSXDir\n" >> randomizerlauncher.ini
BaseMSXDir=$(randomizers/mbc list_rom_for MSX | awk -F ' ' '{print $2}' | awk -F '/' '{print $(NF-1)}'| tail -1)
echo "BaseMSXDir=$BaseMSXDir\n" >> randomizerlauncher.ini
echo "RandomizerBasedir=/media/fat/Scripts/randomizers\n" >> randomizerlauncher.ini
echo "TmpDir=$RandomizerBasedir/taptorandomizetmp\n" >> randomizerlauncher.ini
echo "ArchipelagoDir=$RandomizerBasedir/archipelago-0.5.0-MiSTerFPGA\n" >> randomizerlauncher.ini
echo "HostYamlPath=$RandomizerBaseDir/yamls/host.yaml\n" >> randomizerlauncher.ini
echo "SystemForAutolaunch=none\n" >> randomizerlauncher.ini
echo "KeepSeeds=5\n" >> randomizerlauncher.ini
echo "SolarJetmanRandoDir=SolarJetmanRando" >> randomizerlauncher.ini
rom_hash="4241161793"
rom_filename_pattern="*[Ss]olar*[Jj]etman*.nes"
rom_base_path="$BaseGameDir/$BaseNesDir/"
locate_rom
echo "SolarJetmanRom=\'$found_rom_path\'\n" >> randomizerlauncher.ini
echo "SolarJetmanRandomizeAstronaut=0\n" >> randomizerlauncher.ini
echo "SolarJetmanRandomizePod=0\n" >> randomizerlauncher.ini
echo "SolarJetmanRandomizeItems=1\n" >> randomizerlauncher.ini
echo "SolarJetmanRandomizeItemsWithLogic=0\n" >> randomizerlauncher.ini
echo "SolarJetmanRandomizePallette=1\n" >> randomizerlauncher.ini
echo "SolarJetmanLateral=0\n" >> randomizerlauncher.ini
echo "SolarJetmanSeed=-1\n" >> randomizerlauncher.ini
echo "SolarJetmanMode=normal\n" >> randomizerlauncher.ini
echo "ALTTPRandoDir=ALTTPRando\n" >> randomizerlauncher.ini
echo "ALTTPPlayerDir=alttp\n" >> randomizerlauncher.ini
echo "DKC3RandoDir=DKC3Rando\n" >> randomizerlauncher.ini
echo "DKC3PlayerDir=dkc3\n" >> randomizerlauncher.ini
echo "CV64RandoDir=CV64Rando\n" >> randomizerlauncher.ini
echo "CV64PlayerDir=cv64\n" >> randomizerlauncher.ini
echo "KDL3RandoDir=KDL3Rando\n" >> randomizerlauncher.ini
echo "KDL3PlayerDir=kdl3\n" >> randomizerlauncher.ini
echo "LOZRandoDir=LOZRando\n" >> randomizerlauncher.ini
echo "LOZPlayerDir=loz\n" >> randomizerlauncher.ini
echo "L2RandoDir=L2Rando\n" >> randomizerlauncher.ini
echo "L2PlayerDir=lufia2\n" >> randomizerlauncher.ini
echo "MMBN3RandoDir=MMBN3Rando\n" >> randomizerlauncher.ini
echo "MMBN3PlayerDir=mmbn3\n" >> randomizerlauncher.ini
echo "#PokeERandoDir=PokemonEmeraldRando\n" >> randomizerlauncher.ini
echo "#PokeEPlayerDir=pokemonemerald\n" >> randomizerlauncher.ini
echo "#OOTRandoDir=OOTRando\n" >> randomizerlauncher.ini
echo "#OOTPlayerDir=oot\n" >> randomizerlauncher.ini
echo "PokeRBRandoDir=PokeRBRando\n" >> randomizerlauncher.ini
echo "PokeRBPlayerDir=pokemonrb\n" >> randomizerlauncher.ini
echo "SMWRandoDir=SMWRando\n" >> randomizerlauncher.ini
echo "SMWPlayerDir=smw\n" >> randomizerlauncher.ini
echo "SMZ3RandoDir=SMZ3Rando\n" >> randomizerlauncher.ini
echo "SMZ3PlayerDir=smz3\n" >> randomizerlauncher.ini
echo "SOERandoDir=SOERando\n" >> randomizerlauncher.ini
echo "SOEPlayerDir=soe\n" >> randomizerlauncher.ini
echo "BaseRandoDir=/tmp/rando/\n" >> randomizerlauncher.ini
echo "SMRandoDir=SMRando\n" >> randomizerlauncher.ini
echo "SMPlayerDir=supermetroid\n" >> randomizerlauncher.ini
echo "SMW2RandoDir=YIRando\n" >> randomizerlauncher.ini
echo "SMW2PlayerDir=yoshi\n" >> randomizerlauncher.ini
echo "YGORandoDir=YGORando\n" >> randomizerlauncher.ini
echo "YGOPlayerDir=yugioh\n" >> randomizerlauncher.ini
echo "DQ3RandoDir=DQ3Rando\n" >> randomizerlauncher.ini
rom_hash="2552947004"
rom_filename_pattern="*[Dd]ragon*[Qq]uest*3*.s[mf]c"
rom_base_path="$BaseGameDir/$BaseSnesDir/"
locate_rom
echo "DQ3RomPath=\'$found_rom_path\'\n" >> randomizerlauncher.ini
echo "ZillionRandoDir=ZillionRando\n" >> randomizerlauncher.ini
echo "ZillionPlayerDir=zillion\n" >> randomizerlauncher.ini
echo "COTMRandoDir=COTMRando\n" >> randomizerlauncher.ini
rom_hash="272442857"
rom_filename_pattern="*[Cc]ircle*[Oo]f*[Tt]he*[Mm]oon*.gba"
rom_base_path="$BaseGameDir/$BaseGBADir/"
locate_rom
echo "COTMRomPath=\'$found_rom_path\'\n" >> randomizerlauncher.ini
echo "COTMignoreCleansing=0 \n" >> randomizerlauncher.ini
echo "COTMapplyAutoRunPatch=0 \n" >> randomizerlauncher.ini
echo "COTMapplyNoDSSGlitchPatch=0 \n" >> randomizerlauncher.ini
echo "COTMapplyAllowSpeedDash=0 \n" >> randomizerlauncher.ini
echo "COTMbreakIronMaidens=0 \n" >> randomizerlauncher.ini
echo "COTMlastKeyRequired=0 \n" >> randomizerlauncher.ini
echo "COTMlastKeyAvailable=0 \n" >> randomizerlauncher.ini
echo "COTMapplyBuffFamiliars=0 \n" >> randomizerlauncher.ini
echo "COTMapplyBuffSubweapons=0 \n" >> randomizerlauncher.ini
echo "COTMapplyShooterStrength=0 \n" >> randomizerlauncher.ini
echo "COTMdoNotRandomizeItems=0 \n" >> randomizerlauncher.ini
echo "COTMRandomItemHardMode=0 \n" >> randomizerlauncher.ini
echo "COTMhalveDSSCards=0 \n" >> randomizerlauncher.ini
echo "COTMcountdown=0 \n" >> randomizerlauncher.ini
echo "COTMsubweaponShuffle=0 \n" >> randomizerlauncher.ini
echo "COTMnoMPDrain=0 \n" >> randomizerlauncher.ini
echo "COTMallBossesRequired=0 \n" >> randomizerlauncher.ini
echo "COTMdssRunSpeed=1 \n" >> randomizerlauncher.ini
echo "COTMskipCutscenes=0 \n" >> randomizerlauncher.ini
echo "COTMskipMagicItemTutorials=0 \n" >> randomizerlauncher.ini
echo "COTMnerfRocWing=0\n" >> randomizerlauncher.ini
rom_hash="272442857"
rom_filename_pattern="*[Aa]ct[Rr]aiser*.s[mf]c"
rom_base_path="$BaseGameDir/$BaseSNESDir/"
locate_rom
echo "ARRomPath=\'$found_rom_path\'\n" >> randomizerlauncher.ini
echo "ARRandoDir=ARRando\n" >> randomizerlauncher.ini
echo "ARExtraLives=0\n" >> randomizerlauncher.ini
echo "ARUnlimitedLives=0\n" >> randomizerlauncher.ini
echo "ARDeathCount=1\n" >> randomizerlauncher.ini
echo "ARSwordUpgrade=0\n" >> randomizerlauncher.ini
echo "ARMarhana='N'\n" >> randomizerlauncher.ini
echo "ARBossRush='C'\n" >> randomizerlauncher.ini
echo "BOF3Abilities=1\n" >> randomizerlauncher.ini
echo "BOF3Characters=1\n" >> randomizerlauncher.ini
echo "BOF3Enemies=0\n" >> randomizerlauncher.ini
echo "BOF3DragonLoc=0\n" >> randomizerlauncher.ini
echo "BOF3Masters=0\n" >> randomizerlauncher.ini
echo "BOF3Items=1\n" >> randomizerlauncher.ini
echo "BOF3Shops=1\n" >> randomizerlauncher.ini
echo "BOF3Treasure=1\n" >> randomizerlauncher.ini
echo "BOF3RandoDir=BOF3Rando\n" >> randomizerlauncher.ini
rom_hash="3141103799"
rom_filename_pattern="*[Bb]reath*[Oo]f*[Ff]ire*[3iI]*Track 1*.bin"
rom_base_path="$BaseGameDir/$BasePSXDir/"
locate_rom
echo "BOF3RomPath=\'$found_rom_path\'\n" >> randomizerlauncher.ini
echo "FFTAbilities=1\n" >> randomizerlauncher.ini
echo "FFTMusic=0\n" >> randomizerlauncher.ini
echo "FFTFormations=1\n" >> randomizerlauncher.ini
echo "FFTJobInnates=1\n" >> randomizerlauncher.ini
echo "FFTJobStats=1\n" >> randomizerlauncher.ini
echo "FFTShop=1\n" >> randomizerlauncher.ini
echo "FFTMaps=1\n" >> randomizerlauncher.ini
echo "FFTJobRequirements=1\n" >> randomizerlauncher.ini
echo "FTJobSkillsets=1\n" >> randomizerlauncher.ini
echo "FFTTrophies=1\n" >> randomizerlauncher.ini
echo "FFTUnits=1\n" >> randomizerlauncher.ini
echo "FFTWeapons=1\n" >> randomizerlauncher.ini
echo "FFTStatus=1\n" >> randomizerlauncher.ini
rom_hash="589112002"
rom_filename_pattern="*[Ff]inal*[Ff}antasy*[Tt]actics*.bin"
rom_base_path="$BaseGameDir/$BasePSXDir/"
locate_rom
echo "FFTRomPath=\'$found_rom_path\'\n" >> randomizerlauncher.ini
echo "FFTRandoDir=FFTRando\n" >> randomizerlauncher.ini
rom_hash="3152808421"
rom_filename_pattern="*[Ff]inal*[Ff}antasy*[Ll]egend*[3iI].gb"
rom_base_path="$BaseGameDir/$BaseGameboyDir/"
locate_rom
echo "FFL2Evolutions=1\n" >> randomizerlauncher.ini
echo "FFL2Formations=1\n" >> randomizerlauncher.ini
echo "FFL2Items=1\n" >> randomizerlauncher.ini
echo "FFL2MonsterSkills=1\n" >> randomizerlauncher.ini
echo "FFL2MonsterStats=1\n" >> randomizerlauncher.ini
echo "FFL2MutantSkills=1\n" >> randomizerlauncher.ini
echo "FFL2Shops=1\n" >> randomizerlauncher.ini
echo "FFL2Treasure=1\n" >> randomizerlauncher.ini
echo "FFL2RomPath=\'$found_rom_path\'\n" >> randomizerlauncher.ini
echo "FFL2RandoDir=FFL2Rando\n" >> randomizerlauncher.ini
MGRomPath='/media/fat/cifs/games/NES/randoroms/mg.nes'
MGRandoDir=MGRando
LandstalkerRandoDir=LandstalkerRando
LandstalkerRomPath='/media/fat/cifs/games/Genesis/randoroms/landstalker.md'
LandstalkerPreset='default.json'
ShadowrunRomPath='/media/fat/cifs/games/SNES/randoroms/sr.smc'
ShadowrunRandoDir=ShadowrunRando
ALTTPDRandoDir=ALTTPDoorRando
ALTTPDRomPath='/media/fat/cifs/games/SNES/randoroms/alttp.smc'
LADXRandoDir=LADXRando
LADXRomPath='/media/fat/cifs/games/GAMEBOY/randoroms/ladx.gbc'
MegaManWeapons=1
MegaManPalette=1
MegaManWeakness=1
MegaManBossDamage=1
MegaManMusic=0
MegaManRoll=1
MegaManRompath='/media/fat/cifs/games/NES/randoroms/mm.nes'
MegaManRandoDir=MMRando
[basedirs]
HostYamlPath=/media/fat/Scripts/randomizers/yamls/host.yaml
TmpDir=/media/fat/Scripts/randomizers/taptorandomizetmp/

[alttp-a-yaml]
#ALTTP-Archipelago options to override the YAMLs options
YAMLFilePath=/media/fat/Scripts/randomizers/yamls/alttp/MiSTerPlayerALTTP.yaml
rom_path=/media/fat/cifs/games/SNES/randoroms/alttp.smc
progression_balancing=50
accessibility=items
goal=ganon
mode=open
glitches_required=no_glitches
dark_room_logic=lamp
open_pyramid=goal
crystals_needed_for_gt=6
crystals_needed_for_ganon=7
triforce_pieces_mode=available
triforce_pieces_percentage=150
triforce_pieces_required=20
triforce_pieces_available=30
triforce_pieces_extra=10
entrance_shuffle=vanilla
entrance_shuffle_seed=random
big_key_shuffle=original_dungeon
small_key_shuffle=original_dungeon
key_drop_shuffle=true
compass_shuffle=original_dungeon
map_shuffle=original_dungeon
restrict_dungeon_item_on_boss=false
item_pool=normal
item_functionality=normal
enemy_health=default
enemy_damage=default
progressive=on
swordless=false
dungeon_counters=pickup
retro_bow=false
retro_caves=false
hints=on
scams=off
boss_shuffle=none
pot_shuffle=false
enemy_shuffle=false
killable_thieves=false
bush_shuffle=false
shop_item_slots=0
randomize_shop_inventories=default
shuffle_shop_inventories=false
include_witch_hut=false
randomize_shop_prices=false
randomize_cost_types=false
shop_price_modifier=100
shuffle_capacity_upgrades=off
bombless_start=false
shuffle_prizes=general
tile_shuffle=false
glitch_boots=true
beemizer_total_chance=0
beemizer_trap_chance=60
timer=none
countdown_start_time=10
red_clock_time=-2
blue_clock_time=2
green_clock_time=4
death_link=false
allow_collect=true
ow_palettes=default
uw_palettes=default
hud_palettes=default
sword_palettes=default
shield_palettes=default
heartbeep=normal
heartcolor=red
quickswap=true
menuspeed=normal
music=true
reduceflashing=true
triforcehud=normal
start_inventory=null
start_inventory_from_pool=null
misery_mire_medallion=random
turtle_rock_medallion=random

[dkc3-a-yaml]
YAMLFilePath=/media/fat/Scripts/randomizers/yamls/dkc3/MiSTerPlayerDKC3.yaml
progression_balancing=50
accessibility=items
dk_coins_for_gyrocopter=30
kongsanity=false
level_shuffle=false
difficulty=norml
goal=knautilus
krematoa_bonus_coin_cost=15
percentage_of_extra_bonus_coins=100
number_of_banana_birds=15
percentage_of_banana_birds=100
autosave=true
merry=false
music_shuffle=false
kong_palette_swap=default
starting_life_count=5
start_inventory=null
rom_path=/media/fat/cifs/games/SNES/randoroms/dkc3.sfc

[cv64-a-yaml]
YAMLFilePath=/media/fat/Scripts/randomizers/yamls/cv64/MiSTerPlayerCV64.yaml
progression_balancing=50
accessibility=items
character_stages=both
stage_shuffle=false
warp_order=seed_stage_order
sub_weapon_shuffle=off
spare_keys=off
special1s_per_warp=1
total_special1s=7
draculas_condition=crystal
percent_special2s_required=80
total_special2s=25
bosses_required=12
carrie_logic=false
hard_logic=false
multi_hit_breakables=false
empty_breakables=false
lizard_locker_items=false
shopsanity=false
hard_item_pool=false
shop_prices=vanilla
minimum_gold_price=2
maximum_gold_price=30
post_behemoth_boss=vanilla
room_of_clocks_boss=vanilla
renon_fight_condition=spend_30k
vincent_fight_condition=wait_16_days
bad_ending_condition=kill_vincent
increase_item_limit=true
nerf_healing_items=false
loading_zone_heals=true
invisible_items=vanilla
drop_previous_sub_weapon=false
permanent_powerups=false
ice_trap_percentage=0
ice_trap_appearance=major_only
disable_time_restrictions=false
skip_gondolas=false
skip_waterway_blocks=false
countdown=none
big_toss=false
panther_dash=off
increase_shimmy_speed=false
fall_guard=false
death_link=off
window_color_r=1
window_color_g=5
window_color_b=15
window_color_a=8
background_music=normal
map_lighting=normal
cinematic_experience=false
start_inventory=null
start_inventory_from_pool=null
starting_stage=random
rom_path=/media/fat/cifs/games/N64/randoroms/cv64.z64

[kdl3-a-yaml]
YAMLFilePath=/media/fat/Scripts/randomizers/yamls/kdl3/MiSTerPlayerKDL3.yaml
progression_balancing=50
accessibility=items
death_link=false
game_language=english
goal=zero
goal_speed=normal
total_heart_stars=30
heart_stars_required=50
filler_percentage=50
trap_percentage=50
gooey_trap_weight=50
slow_trap_weight=50
ability_trap_weight=50
jumping_target=10
stage_shuffle=none
boss_shuffle=none
allow_bb=disabled
animal_randomization=disabled
copy_ability_randomization=disabled
strict_bosses=true
open_world=true
ow_boss_requirement=3
boss_requirement_random=false
consumables=false
starsanity=false
gifting=false
kirby_flavor_preset=default
gooey_flavor_preset=default
music_shuffle=none
virtual_console=flash_reduction
start_inventory=null

[loz-a-yaml]
YAMLFilePath=/media/fat/Scripts/randomizers/yamls/loz/MiSTerPlayerLegendOfZelda.yaml
progression_balancing=50
accessibility=items
ExpandedPool=true
TriforceLocations=vanilla
StartingPosition=safe  start_inventory=null
rom_path=/media/fat/cifs/games/NES/randoroms/tloz.nes

[l2ac-a-yaml]
YAMLFilePath=/media/fat/Scripts/randomizers/yamls/lufia2/MiSTerPlayerLufia2.yaml
progression_balancing=50
accessibility=items
blue_chest_chance=25
blue_chest_count=25
boss=master
capsule_cravings_jp_style=false
capsule_starting_form=1
capsule_starting_level=1
crowded_floor_chance=16
death_link=false
default_capsule=jelze
default_party=m
enemy_floor_numbers=vanilla
enemy_movement_patterns=vanilla
enemy_sprites=vanilla
exp_modifier=100
final_floor=99
gear_variety_after_b9=false
goal=boss
gold_modifier=100
healing_floor_chance=16
inactive_exp_gain=disabled
initial_floor=1
iris_floor_chance=5
iris_treasures_required=9
master_hp=9980
party_starting_level=1
run_speed=disabled
shop_interval=1
shuffle_capsule_monsters=false
shuffle_party_members=false
custom_item_pool=null
start_inventory=null
rom_path=/media/fat/cifs/games/SNES/randoroms/l2.smc

[mmbn3-a-yaml]
YAMLFilePath=/media/fat/Scripts/randomizers/yamls/mmbn3/MiSTerPlayerMMBN3.yaml
progression_balancing=50
accessibility=items
extra_ranks=0
include_jobs=true
trade_quest_hinting=full
start_inventory=null
rom_path=/media/fat/cifs/games/GBA/randoroms/mmbn3.gba

[pokerb-a-yaml]
YAMLFilePath=/media/fat/Scripts/randomizers/yamls/pokemonrb/MiSTerPlayerPokemonRB.yaml
progression_balancing=50
accessibility=items
rainer_name=choose_in_game
rival_name=choose_in_game
elite_four_badges_condition=8
elite_four_key_items_condition=0
elite_four_pokedex_condition=0
victory_road_condition=7
route_22_gate_condition=7
viridian_gym_condition=7
cerulean_cave_badges_condition=4
cerulean_cave_key_items_condition=50
route_3_condition=defeat_brock
robbed_house_officer=true
second_fossil_check_condition=3
fossil_check_item_types=any
exp_all=randomize
old_man=early_parcel
badgesanity=false
badges_needed_for_hm_moves=on
key_items_only=false
tea=false
extra_key_items=false
split_card_key=off
all_elevators_locked=true
extra_strength_boulders=false
require_item_finder=false
randomize_hidden_items=off
prizesanity=false
trainersanity=false
dexsanity=0
randomize_pokedex=vanilla
require_pokedex=true
all_pokemon_seen=false
oaks_aide_rt_2=10
oaks_aide_rt_11=20
oaks_aide_rt_15=30
stonesanity=false
door_shuffle=off
warp_tile_shuffle=vanilla
randomize_rock_tunnel=false
dark_rock_tunnel_logic=true
free_fly_location=true
town_map_fly_location=false
blind_trainers=0
minimum_steps_between_encounters=3
level_scaling=auto
exp_modifier=16
randomize_wild_pokemon=vanilla
area_1_to_1_mapping=true
randomize_starter_pokemon=vanilla
randomize_static_pokemon=vanilla
randomize_legendary_pokemon=vanilla
catch_em_all=off
randomize_pokemon_stats=vanilla
randomize_pokemon_catch_rates=false
minimum_catch_rate=3
randomize_trainer_parties=vanilla
trainer_legendaries=false
move_balancing=false
fix_combat_bugs=true
randomize_pokemon_movesets=vanilla
confine_transform_to_ditto=true
start_with_four_moves=false
same_type_attack_bonus=true
randomize_tm_moves=false
tm_same_type_compatibility=0
tm_normal_type_compatibility=0
tm_other_type_compatibility=0
hm_same_type_compatibility=0
hm_normal_type_compatibility=0
hm_other_type_compatibility=0
inherit_tm_hm_compatibility=false
randomize_move_types=false
randomize_pokemon_types=vanilla
secondary_type_chance=0
randomize_type_chart=vanilla
normal_matchups=143
super_effective_matchups=38
not_very_effective_matchups=38
immunity_matchups=6
safari_zone_normal_battles=false
normalize_encounter_chances=false
reusable_tms=false
better_shops=off
master_ball_price=5000
starting_money=3000
lose_money_on_blackout=true
poke_doll_skip=patched
bicycle_gate_skips=patched
trap_percentage=0
poison_trap_weight=medium
fire_trap_weight=medium
paralyze_trap_weight=medium
sleep_trap_weight=medium
ice_trap_weight=disabled
randomize_pokemon_palettes=vanilla
death_link=false
start_inventory=null
game_version=random
red_rom_path=/media/fat/cifs/games/GAMEBOY/randoroms/pokered.gb
blue_rom_path=/media/fat/cifs/games/GAMEBOY/randoroms/pokeblue.gb

[smw-a-yaml]
YAMLFilePath=/media/fat/Scripts/randomizers/yamls/smw/MiSTerPlayerSMW.yaml
progression_balancing=50
accessibility=items
death_link=false
early_climb=false
goal=bowser
bosses_required=7
max_yoshi_egg_cap=50
percentage_of_yoshi_eggs=100
dragon_coin_checks=false
moon_checks=false
hidden_1up_checks=false
bonus_block_checks=false
blocksanity=false
bowser_castle_doors=vanilla
bowser_castle_rooms=random_two_room
level_shuffle=false
exclude_special_zone=false
boss_shuffle=none
swap_donut_gh_exits=false
junk_fill_percentage=0
trap_fill_percentage=0
ice_trap_weight=medium
stun_trap_weight=medium
literature_trap_weight=medium
timer_trap_weight=medium
reverse_trap_weight=medium
thwimp_trap_weight=medium
display_received_item_popups=progression_minus_yoshi_eggs
autosave=true
overworld_speed=vanilla
music_shuffle=none
sfx_shuffle=none
mario_palette=mario
level_palette_shuffle=off
overworld_palette_shuffle=off
starting_life_count=5
start_inventory=null
rom_path=/media/fat/cifs/games/SNES/randoroms/smw.smc

[smz3-a-yaml]
YAMLFilePath=/media/fat/Scripts/randomizers/yamls/smz3/MiSTerPlayerSMZ3.yaml
progression_balancing=50
accessibility=items
sm_logic=normal
sword_location=randomized
morph_location=randomized
goal=defeatboth
key_shuffle=none
open_tower=7
ganon_vulnerable=7
open_tourian=4
spin_jumps_animation=false
heart_beep_speed=normal
heart_color=red
quick_swap=false
energy_beep=true
start_inventory=null
sm_rom_path=/media/fat/cifs/games/SNES/randoroms/sm.smc
z3_rom_path=/media/fat/cifs/games/SNES/randoroms/alttp.smc


[soe-a-yaml]
YAMLFilePath=/media/fat/Scripts/randomizers/yamls/soe/MiSTerPlayerSoE.yaml
progression_balancing=30
accessibility=items
difficulty=normal
energy_core=shuffle
required_fragments=10
available_fragments=11
money_modifier=200
exp_modifier=200
sequence_breaks=off
out_of_bounds=off
fix_cheats=true
fix_infinite_ammo=false
fix_atlas_glitch=false
fix_wings_glitch=false
shorter_dialogs=true
short_boss_rush=true
ingredienizer=on
sniffamizer=shuffle
sniff_ingredients=vanilla_ingredients
callbeadamizer=on
musicmizer=false
doggomizer=off
turdo_mode=false
death_link=false
trap_count=0
trap_chance_quake=20
trap_chance_poison=20
trap_chance_confound=20
trap_chance_hud=20
trap_chance_ohko=20
start_inventory=null
rom_path=/media/fat/cifs/games/SNES/randoroms/soe.smc


[sm-a-yaml]
YAMLFilePath=/media/fat/Scripts/randomizers/yamls/supermetroid/MiSTerPlayerSuperMetroid.yaml
progression_balancing=50
accessibility=items
start_inventory_removes_from_pool=false
preset=regular
start_location=landing_site
remote_items=false
death_link=disable
max_difficulty=hardcore
morph_placement=early
hide_items=false
strict_minors=false
missile_qty=30
super_qty=20
power_bomb_qty=10
minor_qty=100
energy_qty=vanilla
area_randomization=off
area_layout=false
doors_colors_rando=false
allow_grey_doors=false
boss_randomization=false
escape_rando=false
remove_escape_enemies=false
fun_combat=false
fun_movement=false
fun_suits=false
layout_patches=true
varia_tweaks=false
nerfed_charge=false
gravity_behaviour=balanced
elevators_speed=true
fast_doors=true
spin_jump_restart=false
rando_speed=false
infinite_space_jump=false
refill_before_save=false
hud=false
animals=false
no_music=false
random_music=false
tourian=vanilla
custom_objective=false
custom_objective_list=random
custom_objective_count=4
objective=kill all G4
relaxed_round_robin_cf=false
start_inventory=null
rom_path=/media/fat/cifs/games/SNES/randoroms/sm.smc

[smw2-a-yaml]
YAMLFilePath=/media/fat/Scripts/randomizers/yamls/yoshi/MiSTerPlayerYoshi.yaml
progression_balancing=50
accessibility=items
starting_world=world_1
starting_lives=3
goal=bowser
luigi_pieces_required=25
luigi_pieces_in_pool=50
extras_enabled=false
minigame_checks=none
split_extras=false
split_bonus=false
hidden_object_visibility=coins_only
add_secretlens=false
shuffle_midrings=false
stage_logic=strict
item_logic=false
disable_autoscroll=false
softlock_prevention=true
castle_open_condition=5
castle_clear_condition=0
bowser_door_mode=manual
level_shuffle=disabled
boss_shuffle=false
yoshi_colors=normal
yoshi_singularity_color=green
baby_mario_sound=normal
traps_enabled=false
trap_percent=10
death_link=false
start_inventory=null
rom_path=/media/fat/games/cifs/SNES/randoroms/smw2.smc

[ygo-a-yaml]
YAMLFilePath=/media/fat/Scripts/randomizers/yamls/yugioh/MiSTerPlayerYuGiOh.yaml
progression_balancing=50
accessibility=items
structure_deck=random_deck
banlist=september_2005
final_campaign_boss_unlock_condition=campaign_opponents
fourth_tier_5_campaign_boss_unlock_condition=campaign_opponents
third_tier_5_campaign_boss_unlock_condition=campaign_opponents
final_campaign_boss_challenges=10
fourth_tier_5_campaign_boss_challenges=5
third_tier_5_campaign_boss_challenges=2
final_campaign_boss_campaign_opponents=12
fourth_tier_5_campaign_boss_campaign_opponents=7
third_tier_5_campaign_boss_campaign_opponents=3
number_of_challenges=10
starting_money=3000
money_reward_multiplier=20
normalize_boosters_packs=true
booster_pack_prices=100
add_empty_banlist=false
campaign_opponents_shuffle=false
ocg_arts=false
start_inventory=null
rom_path=/media/fat/cifs/games/GBA/randoroms/yugioh06.gba

[zillion-a-yaml]
YAMLFilePath=/media/fat/Scripts/randomizers/yamls/zillion/MiSTerPlayerZillion.yaml
progression_balancing=50
accessibility=items
continues=3
floppy_req=5
gun_levels=balanced
jump_levels=balanced
randomize_alarms=true
max_level=8
opas_per_level=2
early_scope=false
skill=2
starting_cards=2
id_card_count=42
bread_count=50
opa_opa_count=26
zillion_count=8
floppy_disk_count=7
scope_count=4
red_id_card_count=2
start_inventory=null
start_char=random
rom_path=/media/fat/cifs/games/SMS/randoroms/Zillion (UE) [!].sms
